seed: 42
models:
  separate: false
  policy:
    clip_actions: true
    clip_log_std: true
    initial_log_std: 0
    min_log_std: -20.0
    max_log_std: 2.0
    input_shape: Shape.STATES
    hiddens:
    - 64
    - 64
    hidden_activation:
    - elu
    - elu
    - elu
    output_shape: Shape.ACTIONS
    output_activation: tanh
    output_scale: 1.0
  value:
    clip_actions: false
    input_shape: Shape.STATES
    hiddens:
    - 64
    - 64
    hidden_activation:
    - elu
    - elu
    - elu
    output_shape: Shape.ONE
    output_activation: ''
    output_scale: 1.0
agent:
  rollouts: 24
  learning_epochs: 5
  mini_batches: 4
  discount_factor: 0.99
  lambda: 0.95
  learning_rate: 0.0005
  learning_rate_scheduler: KLAdaptiveLR
  learning_rate_scheduler_kwargs:
    kl_threshold: 0.016
  state_preprocessor: RunningStandardScaler
  state_preprocessor_kwargs: null
  value_preprocessor: RunningStandardScaler
  value_preprocessor_kwargs: null
  random_timesteps: 0
  learning_starts: 0
  grad_norm_clip: 1.0
  ratio_clip: 0.2
  value_clip: 0.2
  clip_predicted_values: true
  entropy_loss_scale: 0.0
  value_loss_scale: 1.0
  kl_threshold: 0
  rewards_shaper_scale: 0.01
  experiment:
    directory: /home/vs/Developer/IsaacLab/logs/skrl/quadcopter_direct
    experiment_name: 2024-09-25_04-47-55
    write_interval: 24
    checkpoint_interval: 240
trainer:
  timesteps: 4800
  environment_info: log
